.TH "WSL2" "7" "DATEPLACEHOLDER" "VERSIONPLACEHOLDER" "WSL User Manual"
.SH NAME
.B WSL2
.SH DESCRIPTION
WSL 2 is a new version of the Windows Subsystem for Linux architecture that powers the Windows Subsystem for Linux to run ELF64 Linux binaries on Windows. Its primary goals are to increase file system performance, as well as adding full system call compatibility.
.PP
This new architecture changes how these Linux binaries interact with Windows and your computer's hardware, but still provides the same user experience as in WSL 1 (the current widely available version).
.PP
Individual Linux distributions can be run with either the WSL 1 or WSL 2 architecture. Each distribution can be upgraded or downgraded at any time and you can run WSL 1 and WSL 2 distributions side by side. WSL 2 uses an entirely new architecture that benefits from running a real Linux kernel.
.SH AUTHOR
WSL Documentation created by Microsoft;
.PP
WSL User Manual created by Patrick Wu <me@patrickwu.space>
.SH REPORTING BUGS
Report bugs to <https://github.com/microsoft/WSL/issues>
.SH SEE ALSO
wsl(7)